action: training
data: ../archive/test.csv
model: svm
data_preprocessing:
  to_lowercase: [0]
  remove_nonalphanumerics: [0]
  remove_stopwords: [0]
  lemmatization: [0]
  # stemming: [0]
  # remove_specific:
  #   regex: "[a-z]"
  #   columns: [0] # column numbers
  tokenization: [0]
feature_extraction:
  TF_IDF: true
training:
  features: [0, 1, 2]
  label: [3]
  n_estimators: 100
  max_depth: None
  use_grid_search: true
