action: training
data: ../archive/sample.csv
model: random_forest
data_preprocessing:
  to_lowercase: [0]
  remove_nonalphanumerics: [0]
  remove_stopwords: [0]
  lemmatization: [0]
  # stemming: [0]
  # remove_specific:
  #   regex: "[a-z]"
  #   columns: [0] # column numbers
  tokenization: [0]
feature_extraction:
  # drop: [0]
  TF_IDF: [0]
  # one_hot_encoding: [0]
  # bag_of_words: [0]
  # bag_of_n_grams: [(0, 1, 2)] # ToDo
  # pca: [0]
  # pca_n_components: 2
training:
  features: [0]
  label: [1]
  n_estimators: 100
  max_depth: None
  use_grid_search: true
