action: training
data: ../archive/test.csv
model: svm
data_preprocessing:
  tokenization: [0]
  to_lowercase: [0]
  remove_nonalphanumerics: [0]
  remove_stopwords: [0]
  lemmatization: [0]
feature_extraction:
  TF_IDF: true
training:
  n_estimators: 100
  max_depth: None
  use_grid_search: true
