action: training
data: archive/
model: svm
data_preprocessing:
  tokenization: true
  to_lowercase: true
  remove_nonalphanumerics: true
  remove_stopwords: true
  lemmatization: true
feature_extraction:
  TF_IDF: true
training:
  n_estimators: 100
  max_depth: None
  use_grid_search: true
