action: training
data: /archive/data/sample.csv
model: random_forest
data_preprocessing:
  to_lowercase: [0]
  remove_nonalphanumerics: [0]
  remove_stopwords: [0]
  lemmatization: [0]
  # stemming: [0]
  # remove_specific:
  #   regex: "[a-z]"
  #   columns: [0] # column numbers
  tokenization: [0]
feature_extraction:
  # drop: ["text"]
  # TF_IDF: ["text"]
  # one_hot_encoding: ["text"]
  bag_of_words: ["text"]
  # bag_of_n_grams: [(0, 1, 2)] # ToDo
  # pca: [0] # ToDo
  # pca_n_components: 2
training:
  features: ["text"]
  labels: ["label"]
  # n_estimators: 120
  # max_depth: None
  # use_grid_search: true
